"""
Base Strategy Class
Abstract base for all trading strategies
REQ-STRAT-001 to REQ-STRAT-028
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional
from dataclasses import dataclass
from datetime import datetime
import logging


@dataclass
class StrategySignal:
    """Trading signal generated by strategy"""
    strategy_name: str
    symbol: str
    expiry_date: str
    signal_type: str  # 'ENTRY' or 'EXIT'
    legs: List[Dict]  # List of option legs
    entry_conditions_met: bool
    reason: str
    timestamp: datetime

    # Risk metrics
    max_loss: float
    max_profit: float
    margin_required: float
    position_greeks: Dict[str, float]

    # Strategy-specific parameters
    target_profit_pct: float
    stop_loss_pct: float


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies
    All strategies must inherit from this class
    """

    def __init__(self, config: Dict, name: str):
        """
        Initialize base strategy

        Args:
            config: Strategy configuration
            name: Strategy name
        """
        self.logger = logging.getLogger(f"{__name__}.{name}")
        self.config = config
        self.name = name
        self.enabled = config.get('enabled', True)

        # Common parameters (REQ-STRAT-025, REQ-STRAT-026)
        self.min_dte = config.get('min_dte', 5)
        self.max_dte = config.get('max_dte', 15)
        self.target_profit = config.get('target_profit', 0.50)
        self.stop_loss = config.get('stop_loss', 1.00)

        self.logger.info(f"Strategy '{name}' initialized (enabled={self.enabled})")

    @abstractmethod
    def generate_entry_signal(
        self,
        market_data: Dict,
        option_chain: List[Dict],
        current_positions: List[Dict]
    ) -> Optional[StrategySignal]:
        """
        Generate entry signal based on market conditions
        REQ-STRAT-014 to REQ-STRAT-019

        Args:
            market_data: Current market data (spot, VIX, etc.)
            option_chain: Available options
            current_positions: Existing positions

        Returns:
            StrategySignal if conditions met, None otherwise
        """
        pass

    @abstractmethod
    def check_exit_conditions(
        self,
        position: Dict,
        market_data: Dict,
        current_greeks: Dict
    ) -> tuple[bool, str]:
        """
        Check if position should be exited
        REQ-STRAT-020 to REQ-STRAT-024

        Args:
            position: Current position details
            market_data: Current market data
            current_greeks: Current Greeks for position

        Returns:
            Tuple of (should_exit, reason)
        """
        pass

    @abstractmethod
    def calculate_position_metrics(
        self,
        legs: List[Dict],
        spot_price: float
    ) -> Dict:
        """
        Calculate position risk metrics
        REQ-RISK-001: Calculate max loss and max profit

        Args:
            legs: Option legs of the position
            spot_price: Current spot price

        Returns:
            Dictionary with max_loss, max_profit, margin_required
        """
        pass

    def check_entry_conditions_common(
        self,
        market_data: Dict,
        current_positions: List[Dict]
    ) -> tuple[bool, str]:
        """
        Check common entry conditions for all strategies
        REQ-STRAT-014 to REQ-STRAT-018

        Args:
            market_data: Current market data
            current_positions: Existing positions

        Returns:
            Tuple of (conditions_met, reason)
        """
        # Check if strategy is enabled
        if not self.enabled:
            return False, "Strategy is disabled"

        # Check if already have a position for this strategy
        existing = any(
            pos.get('strategy_name') == self.name
            for pos in current_positions
        )
        if existing:
            return False, f"Already have {self.name} position"

        # Check VIX if applicable (REQ-STRAT-014)
        max_vix = self.config.get('max_vix')
        if max_vix:
            current_vix = market_data.get('vix', 0)
            if current_vix > max_vix:
                return False, f"VIX {current_vix:.2f} > {max_vix}"

        # Check DTE range (REQ-STRAT-015)
        dte = market_data.get('days_to_expiry', 0)
        if dte < self.min_dte or dte > self.max_dte:
            return False, f"DTE {dte} outside range [{self.min_dte}, {self.max_dte}]"

        # Check trading time window (REQ-STRAT-017)
        current_time = datetime.now()
        if not self._is_within_trading_window(current_time):
            return False, "Outside trading window"

        return True, "Common conditions met"

    def _is_within_trading_window(self, current_time: datetime) -> bool:
        """
        Check if current time is within trading window
        REQ-STRAT-017: Validate trading time window
        """
        # Get trading window from config (default: 9:20 AM - 3:00 PM)
        start_hour = 9
        start_minute = 20
        end_hour = 15
        end_minute = 0

        start_time = current_time.replace(hour=start_hour, minute=start_minute, second=0)
        end_time = current_time.replace(hour=end_hour, minute=end_minute, second=0)

        return start_time <= current_time <= end_time

    def validate_strategy_whitelist(self) -> bool:
        """
        Ensure strategy is not prohibited
        REQ-RISK-022 to REQ-RISK-026
        """
        prohibited = [
            'naked_call',
            'naked_put',
            'short_straddle_unhedged',
            'short_strangle_unhedged'
        ]

        strategy_lower = self.name.lower().replace(' ', '_')
        return strategy_lower not in prohibited

    def log_signal(self, signal: Optional[StrategySignal]):
        """Log generated signal"""
        if signal:
            self.logger.info(
                f"📊 {signal.signal_type} SIGNAL: {signal.strategy_name} "
                f"{signal.symbol} | Max Loss: ₹{signal.max_loss:.2f} | "
                f"Max Profit: ₹{signal.max_profit:.2f} | Reason: {signal.reason}"
            )
        else:
            self.logger.debug(f"No signal generated for {self.name}")
